### ISSUE TITLE
Modification du fichier EX_TreatmentNumbers.fsh 

### ISSUE THREAD

**Issue by nlebuhan-Kereval** [ONCOFAIR/FHIR-ImplementationGuide-Article#11]
## Description du problème
Dans le fichier EX_TreatmentNumbers.fsh, il y a deux extensions présentes : 
TreatmentCycleNumber et TreatmentDayNumber

## Fichier•s concerné•s
EX_TreatmentNumbers.fsh

## Solution proposée
Je pense qu'il serait bien de créer un fichier différent pour chaque extension.

**Comment by mbrulliard** [comment]
Le fichier a été supprimé, le problème est donc supprimé également
